server:
  port: 8888

spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      discovery:
        namespace: 00eec62c-3c40-4309-8541-466dd67aff5a
        server-addr: 127.0.0.1
    gateway:
      routes:
        - id: user-demo
          uri: lb://user-demo
          predicates:
            - Path=/user/**    # 断言，路径相匹配的进行路由
          filters:
            - AddRequestHeader=X-Request-name,red #添加请求头
      httpclient:
        connect-timeout: 5
        response-timeout: 15